{
  "openapi": "3.0.3",
  "info": {
    "title": "CodeStacker API",
    "version": "1.0.0",
    "summary": " APIs to upload, parse, and store PDF files. Written by Alqasim Alzakwani",
    "contact": {
      "name": "Alqasim Alzakwani",
      "email": "q.zak003@gmail.com"
    }
  },
  "components": {
    "securitySchemes": {
      "Basic": { "type": "http", "scheme": "basic" }
    }
  },
  "security": [{ "Basic": [] }],
  "servers": [{ "url": "http://127.0.0.1:8000", "description": "Main server" }],

  "tags": [
    {
      "name": "Account"
    },
    {
      "name": "PDF"
    },
    {
      "name": "Search"
    }
  ],

  "paths": {
    "/account/sign-up/": {
      "post": {
        "security": [],
        "operationId": "1",
        "tags": ["Account"],
        "summary": "Sign up new account",
        "description": "Use this endpoint to register new account for authenticating the other endpoints.\n\nNote: There is no requirements for valid username and password. Could be anything.",
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": ["username", "password"],
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "username": "alqasim",
                "password": "alzakwani"
              }
            },
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["username", "password"],
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "username": "alqasim",
                "password": "alzakwani"
              }
            }
          }
        },

        "responses": {
          "201": {
            "description": "Account created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "username": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "username": "alqasim"
                }
              }
            }
          },

          "400": {
            "description": "Account creation failed",
            "content": {
              "application/json": {
                "example": {
                  "username": ["A user with that username already exists."],
                  "password": ["This field is required."]
                }
              }
            }
          }
        }
      }
    },

    "/pdf/upload/": {
      "post": {
        "operationId": "2",
        "tags": ["PDF"],
        "summary": "Upload new PDFs",
        "description": "Use this endpoint to upload PDF files.\n\nNote that you can upload multiple files.",
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": ["file"],
                "properties": {
                  "file": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "File/s uploaded",
            "content": {
              "application/json": {
                "example": {
                  "success": "file/s uploaded",
                  "file/s": [
                    {
                      "file_name": "pfd.pdf",
                      "size": 64723,
                      "parsing_status": "IN PROCESS",
                      "time_of_upload": "SOME-TIME-DATE+TIMEZONE"
                    }
                  ]
                }
              }
            }
          },

          "400": {
            "description": "Failed upload",
            "content": {
              "application/json": {
                "example": {
                  "error": "file pdf.pdf already exists!"
                }
              }
            }
          }
        }
      }
    },

    "/pdf/list/": {
      "get": {
        "operationId": "3",
        "tags": ["PDF"],
        "summary": "List ALL files",
        "description": "Use this endpoint to all files at once.",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 14,
                    "file_name": "m.pdf",
                    "size": 129117,
                    "number_of_pages": 8,
                    "time_of_upload": "2023-04-13T14:15:09.885872+04:00"
                  },
                  {
                    "id": 13,
                    "file_name": "H.pdf",
                    "size": 27465,
                    "number_of_pages": 1,
                    "time_of_upload": "2023-04-13T14:07:26.290963+04:00"
                  }
                ]
              }
            }
          }
        }
      },

      "post": {
        "operationId": "4",
        "tags": ["PDF"],
        "summary": "Paginate the list",
        "description": "Use this endpoint to list the files with pagination.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "paginate": {
                    "type": "number"
                  },
                  "page": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "paginate": 20,
                "page": 1
              }
            },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "paginate": {
                    "type": "number"
                  },
                  "page": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "paginate": 20,
                "page": 1
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "page": "1 of 10",
                  "results": [
                    {
                      "id": 14,
                      "file_name": "m.pdf",
                      "size": 129117,
                      "number_of_pages": 8,
                      "time_of_upload": "2023-04-13T14:15:09.885872+04:00"
                    },
                    {
                      "id": 13,
                      "file_name": "H.pdf",
                      "size": 27465,
                      "number_of_pages": 1,
                      "time_of_upload": "2023-04-13T14:07:26.290963+04:00"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },

    "/pdf/get/{id}/": {
      "get": {
        "operationId": "5",
        "tags": ["PDF"],
        "summary": "Get pdf data",
        "description": "Use this endpoint to get one pdf data with its ID.",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id",
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "id": 13,
                  "file_name": "H.pdf",
                  "size": 27465,
                  "number_of_pages": 1,
                  "time_of_upload": "2023-04-13T14:07:26.290963+04:00"
                }
              }
            }
          },

          "404": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "error": "pdf file with ID:7 NOT FOUND"
                }
              }
            }
          }
        }
      }
    },

    "/pdf/download/{id}/": {
      "get": {
        "operationId": "6",
        "tags": ["PDF"],
        "summary": "Download pdf",
        "description": "Use this endpoint to retrieve pdf file with its ID.",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id",
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/pdf": {}
            }
          },

          "404": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "error": "pdf file with ID:7 NOT FOUND"
                }
              }
            }
          }
        }
      }
    },

    "/pdf/list-sentences/{id}/": {
      "get": {
        "operationId": "7",
        "tags": ["PDF"],
        "summary": "List pdf's sentences",
        "description": "Use this endpoint to retrieve all pdf's parsed sentences with its ID.",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id",
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "id": 12,
                  "name": "ra.pdf",
                  "sentences": [
                    "Water is an essential component of life",
                    "...."
                  ]
                }
              }
            }
          },

          "404": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "error": "pdf file with ID:7 NOT FOUND"
                }
              }
            }
          }
        }
      }
    },

    "/pdf/delete/{id}/": {
      "delete": {
        "operationId": "8",
        "tags": ["PDF"],
        "summary": "Delete pdf",
        "description": "Use this endpoint to delete a pdf and all its related data with its ID.",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id",
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "success": "pdf: name.pdf DELETED"
                }
              }
            }
          },

          "404": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "error": "pdf file with ID:7 NOT FOUND"
                }
              }
            }
          }
        }
      }
    },

    "/pdf/parsing-status/{id}/": {
      "get": {
        "operationId": "9",
        "tags": ["PDF"],
        "summary": "Get pdf's parsing status",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id",
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "file": "name.pdf",
                  "parsing_status": "DONE"
                }
              }
            }
          },

          "404": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "error": "pdf file with ID:7 NOT FOUND"
                }
              }
            }
          }
        }
      }
    },

    "/pdf/{id}/download/{page}/": {
      "get": {
        "operationId": "10",
        "tags": ["PDF"],
        "summary": "Get page as image",
        "description": "Use this endpoint to get a page from a pdf as an image with the pdf's id and the page number.\n\nNote: the image here is with default options -> resolution=96 dpi, format=jpeg\n\nIf you want to control these parameters, use the 'POST' endpoint.",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id",
            "schema": {
              "type": "number"
            }
          },
          {
            "in": "path",
            "required": true,
            "name": "page",
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "image/jpeg": {}
            }
          },

          "404": {
            "description": "",
            "content": {
              "application/json": {
                "examples": {
                  "error1": {
                    "summary": "",
                    "value": { "error": "pdf file with ID:7 NOT FOUND" }
                  },

                  "error2": {
                    "summary": "",
                    "value": {
                      "error": "page 5 not in pdf: name.pdf | Possible Pages: 1-3"
                    }
                  }
                }
              }
            }
          }
        }
      },

      "post": {
        "operationId": "11",
        "tags": ["PDF"],
        "summary": "Get page as image with options",
        "description": "Read 'GET' method description to understand this endpoint.\n\nNote: the only available format are ['jpeg' (default), 'png']",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id",
            "schema": {
              "type": "number"
            }
          },
          {
            "in": "path",
            "required": true,
            "name": "page",
            "schema": {
              "type": "number"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "dpi": {
                    "type": "number"
                  },
                  "format": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "dpi": 110,
                "format": "png"
              }
            },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "dpi": {
                    "type": "number"
                  },
                  "format": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "dpi": 110,
                "format": "png"
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "",
            "content": {
              "image/png": {}
            }
          },

          "404": {
            "description": "",
            "content": {
              "application/json": {
                "examples": {
                  "error1": {
                    "summary": "",
                    "value": { "error": "pdf file with ID:7 NOT FOUND" }
                  },

                  "error2": {
                    "summary": "",
                    "value": {
                      "error": "page 5 not in pdf: name.pdf | Possible Pages: 1-3"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/search/": {
      "post": {
        "operationId": "12",
        "tags": ["Search"],
        "summary": "Search for the existence of a keyword",
        "description": "This endpoint search for the existence of a certain keyword in ALL PDF files. It returns all the sentences the word was found in with their PDF ID.\n\nNote: This will search for a word as given exactly (case-insensitive). So if searched for 'help', results with 'helps', 'helping' WILL NOT be returned!\n\nNote: This endpoint can be paginated! (OPTIONAL)\n\nIMPORTANT: for more capable search use '/search/advanced/' (check docs below).",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["search"],
                "properties": {
                  "search": {
                    "type": "string"
                  },
                  "paginate": {
                    "type": "number"
                  },
                  "page": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "search": "keyword (REQUIRED)",
                "paginate": 100,
                "page": 12
              }
            },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": ["search"],
                "properties": {
                  "search": {
                    "type": "string"
                  },
                  "paginate": {
                    "type": "number"
                  },
                  "page": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "search": "keyword (REQUIRED)",
                "paginate": 100,
                "page": 12
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "Search result",
            "content": {
              "application/json": {
                "examples": {
                  "Default": {
                    "summary": "Without pagination",
                    "value": [
                      {
                        "pdf_ID": 3,
                        "sentence": "This is sentence 1 keyword"
                      },
                      {
                        "pdf_ID": 16,
                        "sentence": "KeyWord in sentence 2"
                      }
                    ]
                  },

                  "Another": {
                    "summary": "With pagination",
                    "value": {
                      "page": "12 of 213",
                      "results": [
                        {
                          "pdf_ID": 3,
                          "sentence": "This is sentence 1 keyword"
                        },
                        {
                          "pdf_ID": 16,
                          "sentence": "KeyWord in sentence 2"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "search": ["This field is required."]
                }
              }
            }
          }
        }
      }
    },

    "/search/advanced/": {
      "post": {
        "operationId": "13",
        "tags": ["Search"],
        "summary": "Advanced search",
        "description": "This endpoint is more capable than the regular search.\n\nUSE: [mode]:[search]\n\nAvailable modes: ['def', 'c', 'ic', 'e', 'ie', 'sw', 'isw', 'ew', 'iew', 'ph', 'eng']\n\nExample: using the same example in regular search, if you search 'ic:help', results with 'helps', 'helping' WILL be returned.\n\nTo understand all modes and how to use them, please visit the home page and check 'Advanced Search' page. The home page has a path of '/' or go to http://localhost:8000/",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["search"],
                "properties": {
                  "search": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "search": "eng:what ever search (REQUIRED)"
              }
            },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": ["search"],
                "properties": {
                  "search": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "search": "eng:what ever search (REQUIRED)"
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "Search result",
            "content": {
              "application/json": {
                "example": {
                  "mode": "eng",
                  "count": 2,
                  "results": [
                    {
                      "pdf_ID": 2,
                      "sentence": "result one"
                    },
                    {
                      "pdf_ID": 5,
                      "sentence": "result two"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "examples": {
                  "error1": {
                    "summary": "Wrong format",
                    "value": {
                      "error": "invalid advance search format. MUST BE: [mode]:[search]."
                    }
                  },

                  "error2": {
                    "summary": "Missing search",
                    "value": {
                      "search": ["This field is required."]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/search/advanced-modes/": {
      "get": {
        "operationId": "14",
        "tags": ["Search"],
        "summary": "List Available modes",
        "description": "Use this endpoint to check available advanced search modes.",

        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "Available Advance Search Modes": [
                    "c",
                    "ic",
                    "e",
                    "ie",
                    "sw",
                    "isw",
                    "ew",
                    "iew",
                    "ph",
                    "eng",
                    "def"
                  ]
                }
              }
            }
          }
        }
      }
    },

    "/search/count-word/{id}/{word}/": {
      "get": {
        "operationId": "15",
        "tags": ["Search"],
        "summary": "Occurrence of a word",
        "description": "Use this endpoint to get the total number of times the word is found, in addition to all the sentences the word is found in.",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id",
            "schema": {
              "type": "number"
            }
          },
          {
            "in": "path",
            "required": true,
            "name": "word",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "pdf_ID": 12,
                  "word": "hello",
                  "count": 3,
                  "sentences": ["Hello World.", "Say hello, HELLO!"]
                }
              }
            }
          },

          "404": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "error": "pdf file with ID:{id} NOT FOUND"
                }
              }
            }
          }
        }
      }
    },

    "/search/top5/{id}/": {
      "get": {
        "operationId": "16",
        "tags": ["Search"],
        "summary": "Top 5 occurring words",
        "description": "Use this endpoint to get the 5 most used words in a PDF file. This ignores stop words like (is, but, and, ...etc). To see all stop words check that endpoint (below).\n\nIMPORTANT: to vary these parameters (namely: the number of top words and the collection of stop words) please check the 'POST' endpoint (below).",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id",
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "water": 26,
                  "essential": 5,
                  "resources": 5,
                  "environment": 4,
                  "human": 3
                }
              }
            }
          },

          "404": {
            "description": "",
            "content": {
              "application/json": {
                "example": { "error": "pdf file with ID:7 NOT FOUND" }
              }
            }
          }
        }
      },

      "post": {
        "operationId": "17",
        "tags": ["Search"],
        "summary": "Top occurring words",
        "description": "This endpoint allows you to change the number of top words it returns and the words you want it to ignore (not just the predefined ones, you can check that list with '/search/stop-words/' below).\n\nNOTE: you can specify any amount of top words and words to ignore (for this check USE).\n\nUSE: 'word1,word2,word3' -> as you can see the words must be separated by a comma!",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "id",
            "schema": {
              "type": "number"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "top": {
                    "type": "number"
                  },
                  "ignore": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "top": 3,
                "ignore": "water,essential"
              }
            },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "top": {
                    "type": "number"
                  },
                  "ignore": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "top": 3,
                "ignore": "water,spring"
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "resources": 5,
                  "environment": 4,
                  "human": 3
                }
              }
            }
          },

          "404": {
            "description": "",
            "content": {
              "application/json": {
                "example": { "error": "pdf file with ID:7 NOT FOUND" }
              }
            }
          }
        }
      }
    },

    "/search/stop-words/": {
      "get": {
        "operationId": "18",
        "tags": ["Search"],
        "summary": "List stop words",
        "description": "Use this endpoint to check the stop words used to filter the top 5.",

        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "stop_words": [
                    "a",
                    "about",
                    "actually",
                    "almost",
                    "also",
                    "although",
                    "always",
                    "am",
                    "an",
                    "..."
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
}
